# Generated by Django 3.2.11 on 2023-04-17 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User_ID', models.CharField(max_length=20)),
                ('NickName', models.CharField(max_length=15)),
                ('Password', models.CharField(max_length=25)),
                ('Email', models.EmailField(max_length=254)),
                ('Phone_number', models.CharField(blank=True, max_length=17)),
                ('Profile_photo', models.ImageField(upload_to='')),
                ('Register_time', models.DateTimeField()),
            ],
        ),
    ]
