# Generated by Django 3.2.11 on 2023-04-17 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='id',
        ),
        migrations.AlterField(
            model_name='user',
            name='User_ID',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
