# Generated by Django 3.2.11 on 2023-04-23 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_auto_20230417_1539'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Background_photo',
            field=models.ImageField(blank=True, upload_to='profile_photos/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='Profile_photo',
            field=models.ImageField(upload_to='profile_photos/'),
        ),
    ]
