# Generated by Django 3.2.11 on 2023-05-10 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_auto_20230423_2027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Background_photo',
            field=models.ImageField(blank=True, upload_to='background_photos/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='Profile_photo',
            field=models.ImageField(default='defaultimgs/dfpp.jpg', upload_to='profile_photos/'),
        ),
    ]
