# Generated by Django 3.2.11 on 2023-05-14 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0004_auto_20230510_1543'),
        ('video', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='User',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='User.user', verbose_name='作者'),
        ),
        migrations.AlterField(
            model_name='video',
            name='Classification',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='video.classification', verbose_name='分区'),
        ),
    ]
