# Generated by Django 3.2.11 on 2023-05-15 06:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0002_auto_20230514_1836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='VideoFile',
            field=models.FileField(upload_to='video/', validators=[django.core.validators.FileExtensionValidator(['mp4'])], verbose_name='视频文件'),
        ),
    ]
