# Generated by Django 3.2.11 on 2023-05-15 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0003_alter_video_videofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='Content',
            field=models.CharField(default='该用户很懒，it什么也没有说！', max_length=500, verbose_name='视频简介'),
        ),
        migrations.AlterField(
            model_name='video',
            name='Title',
            field=models.CharField(max_length=100, verbose_name='视频名称'),
        ),
    ]
